### PR TITLE
chore(logger): logger first try on issue #84

### PR DESCRIPTION
**Pull request by vegarringdal**
info:
- all logs gets pushed out to file
- no timer for when messages get pushed to file (its really fast)
- we dont have anything to know if electron crashed

The is much room for improvement, but have to start somewhere

### CODE REVIEW

**Comment by JeroenVinke** [comment]
nice work :+1: 

> no timer for when messages get pushed to file (its really fast)

I know, but this is why I think we should do it anyway:

1. other (intensive) actions may be slowed down by this
2. we don't need to write to disk that much
3. we should not waste CPU cycles on this
4. if we write to disk too much, then there's a bigger chance that the logfile has been locked by other write efforts, and that'll cause exceptions

> we dont have anything to know if electron crashed

do you mean that we can't crash monterey to test?

**Comment by vegarringdal** [comment]
Ill add a timer

> do you mean that we can't crash monterey to test?
Looks like there is no event for it
http://electron.atom.io/docs/api/crash-reporter/
This one does not look useful atm... 

But anyways Ill start with a timer

**Comment by adriatic** [comment]
Great feature, @JeroenVinke @vegarringdal

**Comment by adriatic** [comment]
@JeroenVinke asks:
| do you mean that we can't crash monterey to test?

This is the point in time when one of my favorite constructs (Monterey back end simulator) would kick in :smiley_cat:

**Comment by vegarringdal** [comment]
Added the timer, default is set to 10 sec, and if all windows is closed it tried to flush the buffer in case something have not been written to disk

**Pull request merged**
