### PR TITLE
Adding v-grid and styling of left project menu

### PR DESCRIPTION
**Pull request by vegarringdal**
Tell me if you want to change anything, Im sure there will always be some parts here and there we want to adjust, styling is hard! :smile:

### CODE REVIEW

**Comment by Thanood** [comment]
Try to set `line-height` of the header to the height of the header column so the text is vertically centered. :smile:

**Comment by vegarringdal** [comment]
Will do

**Comment by vegarringdal** [comment]
Does this look better?

image

**Comment by Thanood** [comment]
A bit too much now. :smile: 
I guess you have some paddings or margins somewhere which add to `100%` line-height.

**Comment by vegarringdal** [comment]
Better ? :smile: 
image

**Comment by Thanood** [comment]
:+1:

**Comment by JeroenVinke** [comment]
@vegarringdal can I merge this?

**Comment by vegarringdal** [comment]
Depends on if you are planing a response layout for the left menu/side, dunno how it will act really. 
Since there is no way I can detect those changes(far as a I know) and adjust created rows etc..

**Comment by JeroenVinke** [comment]
> Depends on if you are planing a response layout for the left menu/side,

nope, not right now atleast

**Comment by vegarringdal** [comment]
Then if you want it it should be good :-) 
Atm on my computer Ive been testing so many different parts that nothing is working here... hehe

**Comment by vegarringdal** [comment]
Looks like there is conflicts also today, Im will download it all again, so I get what I did a PR on and have another look

**Comment by JeroenVinke** [comment]
@vegarringdal no need, i'm already merging it

**Comment by vegarringdal** [comment]
k

**Pull request merged**
