### PR TITLE
fix(file-system-logger): fix log file date format

### PR DESCRIPTION
**Pull request by Thanood**
`2016-010-08` => `2016-10-08` 😃

### CODE REVIEW

**Comment by JeroenVinke** [comment]
So https://github.com/monterey-framework/monterey/commit/531e87ab545bee439fe66c4eb5e91318f29f1629 did not fix this issue?

**Comment by JeroenVinke** [comment]
I think we still need to release this commit though

**Comment by Thanood** [comment]
Oh, I didn't see this.

**Comment by vegarringdal** [comment]
Did I make it so months had 3 numbers when over 9 ?

**Comment by JeroenVinke** [comment]
appears so 😄 started noticing it at the start of this month (10)

**Comment by vegarringdal** [comment]
Hehe

```let month = date.getMonth().toString().length === 1 ? '0' + (date.getMonth() + 1) : date.getMonth() + 1;```

I can see I had a plan, just forgot to add the +1 before checking the length 😂 
I did it too early in the year 😄

**Comment by JeroenVinke** [comment]
Closing this one as there is an unreleased commit that fixes this same issue (I should have created an issue  instead of immediately fixing the problem)

**Pull request closed without merging**
