### PR TITLE
chore(terminal): terminal plugin

### PR DESCRIPTION
**Pull request by vegarringdal**
Pushing this before I loose the code, incase you want to use some of it
Not the best, have made it so it exits/kill the process when you go "back"
it supports control+c for making something like gulp watch quit
how it looks atm:

image

### CODE REVIEW

**Comment by vegarringdal** [comment]
rebuilt it

[video](https://drive.google.com/file/d/0B_wM5SJf8IXoRkE1RnBWbGpsVzA/view?usp=sharing)

image

**Comment by vegarringdal** [comment]
Video of terminal work: https://drive.google.com/file/d/0B_wM5SJf8IXoRElsNkZQcGRkV1U/view

Wee need to have a look on the native modlues in electron before we can use this, but its gotten a lot better :-)

**Comment by adriatic** [comment]
@vegarringdal - this is simply fabulous. Thanks for persisting on this colors feature

**Comment by vegarringdal** [comment]
@adriatic thx
But pty.js Im using is a native module, so a bit unsure if it will cause a lot of issues.
Hopefully it wont be much issues, just need to do a lot more testing/reading.

**Comment by JeroenVinke** [comment]
can I merge this (tomorrow)?

**Comment by vegarringdal** [comment]
For me you can merge this now unless you se something that bad ?

I could maybe add a small input so people could name their terminal, incase they have many open ?

**Comment by JeroenVinke** [comment]
Or just call it terminal 1, terminal 2 etc. Just realized that you needed more time to look into using a custom element. So let me know when you have that :)

**Comment by vegarringdal** [comment]
I was think custom element could be later
Now we have a terminal, lets see if we find any bugs etc, so we know more clear what we need the custom element to to.
When we make this we get to test it against the terminal in the app

Regarding naming

image

You can start editing in the header if you want to rename

image

The list wil also update then..
image

**Comment by JeroenVinke** [comment]
:+1:

**Pull request merged**
