### PR TITLE
chore(logger) added the delete after x days, and misc edit on errors #131

### PR DESCRIPTION
**Pull request by vegarringdal**

### CODE REVIEW

**Comment by JeroenVinke** [comment]
I have a git challenge for you :smile: 

can you rename the commit to "feat(logger): delete log after x days" ? its a feature and you missed the `:` in the current commit message

**Comment by JeroenVinke** [comment]
chore's won't be shown in the changelog, so please use `feat` or `fix`  for the things you want to be in the changelog

**Comment by vegarringdal** [comment]
Before I push it, is this how you wanted it?, "amend last commit"
image

**Comment by JeroenVinke** [comment]
Yep message is fine. You probably need to force push

**Comment by vegarringdal** [comment]
great, its pushed now :-)

**Comment by JeroenVinke** [comment]
nice job :+1:

**Pull request merged**
